LOCAL_PATH := $(my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := Nextcloud
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Apps/nextcloud.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_OVERRIDES_PACKAGES :=

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Davdroid
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Apps/davdroid.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_OVERRIDES_PACKAGES :=

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE        := Bromite
ifeq ($(TARGET_ARCH), arm64)
LOCAL_SRC_FILES     := Apps/arm64_ChromePublic.apk
else
LOCAL_SRC_FILES     := Apps/arm_ChromePublic.apk
endif
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE_CLASS  := APPS
LOCAL_CERTIFICATE   := PRESIGNED
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_OVERRIDES_PACKAGES := Browser Browser2 QuickSearchBox
ifeq ($(TARGET_ARCH), arm64)
LOCAL_MULTILIB := 64
else
LOCAL_MULTILIB := 32
endif

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Etar
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := Apps/etar.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_OVERRIDES_PACKAGES := Calendar

include $(BUILD_PREBUILT)
